### PR TITLE
Updated supported Angular major version

### LINKED ISSUE #61: Angular v15 update
**Is your feature request related to a problem? Please describe.**
I am using Angular livechat widget package in the Angular app. I would like to have the latest version supported.

**Describe the solution you'd like**
PR - https://github.com/livechat/chat-widget-adapters/pull/60

### PR DESCRIPTION
**Pull request by ectuser**
### Type of change

- [ ] Docs
- [ ] Bug fix
- [x] Feature

### Packages

- [ ] @livechat/widget-core
- [ ] @livechat/widget-react
- [ ] @livechat/widget-vue
- [x] @livechat/widget-angular

### Issue

https://github.com/livechat/chat-widget-adapters/issues/61

Update Angular peer dependency to the latest v15.  

### Description

Add Angular 14 to @livechat/widget-angular supported peer dependencies.

Tested in the Angular 15 app. Works correctly, no issues spotted

### CODE REVIEW

**Comment by walaszczykm** [comment]
Hello @ectuser, thank you very much for the PR! 🙌  Would you be able also to update the Angular version to the newest one in our example app used for tests? It's located in `examples/angular`; that way, we can verify that everything is working on the prepared setup using automated tests. 🙂

**Comment by ectuser** [comment]
Hello @walaszczykm! Thank you for your response! I migrated the example Angular app to the v14. Then tests started to failing because of some jest issue: `Cannot find module '@angular/core/testing' from 'node_modules/jest-preset-angular/build/config/setup-jest.js'`. For now I do not know how to fix it. If you have time, can you please take a look?

**Comment by walaszczykm** [comment]
Thanks, @ectuser 🙌  I will take a look into that, don't worry 🙂

**Comment by walaszczykm** [comment]
Ok @ectuser, it looks like an issue with imports resolution inside `jest-preset-angular/setup-jest`, which tries to import `@angular/core/testing` using `require`, which, after updating the Angular version, fails as the module's package.json now uses exports keyword without nested package.json files. 

For those tests to set up for Jest, we need `zone.js` so we can get around this issue by importing it directly instead of the entire setup script. That way, simply replace this line in `packages/widget-angular/jest.setup.js`:
```js
import 'jest-preset-angular/setup-jest'
```

with 

```js
import 'zone.js'
```

and everything should work as expected and tests should pass (tested on my side locally).

Just please do not uninstall the `jest-preset-angular` as it is still used as preset in `jest.config.json` we only want to simplify the setup script 🙂

**Review by walaszczykm — APPROVED** [review]
Hello @ectuser, I have re-checked your changes, and everything looks great. Thank you very much for your contribution 🙂

**Pull request merged**
